version: 2.1
workflows:
  testingAllDaRunners:
    jobs:
      - boopTest
      - testTest
jobs:
  boopTest:
    machine: true
    resource_class: livmade/boop
    steps:
      - run: echo "Do you like chocolate?"
  testTest:
    machine: true
    resource_class: livmade/this_is_a_test
    steps:
      - run: echo "Yes, I do"