version: 2.1

workflows:
  runner-stuff-docker:
    jobs:
      - runner1
      - runner2
      - runner3
      - runner4
      - runner5
      - runner6
  scaling-macos:
    jobs:
      - scale
 # other-runners-windows:
 #   jobs:
  #    - windows

jobs:
  scale:
    machine: true
    resource_class: livmade/boop
    steps:
      - checkout
      - run: whoami
      - run: uname
      - run: echo "Bonjour, I am runner on Mac."
      - run: sh ./scale.sh

  runner1:
    machine: true
    resource_class: livmade/docker
    steps:
      - run: echo "Hi I'm runner job 1 on Docker!"

  runner2:
    machine: true
    resource_class: livmade/docker
    steps:
      - run: echo "Hi I'm runner job dos on Docker!"
  runner3:
    machine: true
    resource_class: livmade/docker
    steps:
      - run: echo "Hi I'm runner job trois on Docker!"
  runner4:
    machine: true
    resource_class: livmade/docker
    steps:
      - run: echo "Hi I'm runner job shi on Docker!!"
  runner5:
    machine: true
    resource_class: livmade/docker
    steps:
      - run: echo "Hi I'm runner job cinque on Docker!"
  runner6:
    machine: true
    resource_class: livmade/docker
    steps:
      - run: echo "Hi I'm runner job six on Docker! We are finished."
#  windows:
#    machine: true
#    resource_class: livmade/windows
#    steps:
#      - run: echo "And, lastly! I am Runner on an Azure-Hosted Windows Server VM! We all work!"